[package]
name = "df2"
version = "0.1.0"
edition = "2021"

[dependencies]
app = { path = "crates/app" }


[workspace]
resolver = "2" # Important! wgpu/Bevy needs this!

members = [
    "crates/app",
    "crates/bevy",
]
