[package]
name = "rust-game-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "0.4"
prost = "0.5"
bevy = "0.10.0"

[build-dependencies]
prost-build = "0.5"