[package]
name = "dorf-sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dorf-lib = { path="../dorf-lib" }
